manifest:
  remotes:
  - name: zmkfirmware
    url-base: https://github.com/zmkfirmware
  - name: danielnordqvist
    url-base: https://github.com/danielnordqvist
  projects:
  - name: zmk
    remote: zmkfirmware
    revision: main
    import: app/west.yml
  - name: zmk-driver-azoteq-iqs5xx
    remote: danielnordqvist
    revision: main
